[flutter-aot] Do not assign to final or const variables.
Instead of assigning to final or const variables, throw a
NoSuchMethodError.  Also, triage a few other tests which fail due to
Rasta (Dart2js) behavior.

R=kustermann@google.com

Review URL: https://chromereviews.googleplex.com/470977014 .